/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'paymentProcessingStep': EventHandler<never, { topic: 'payment.processed'; data: never }>
    'orderFulfillmentStep': EventHandler<never, never>
    'orderSubmissionAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'order.created'; data: never }>
    'inventoryUpdateStep': EventHandler<never, { topic: 'inventory.updated'; data: never }>
  }
    
}